// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bb_clientd/bb_clientd.proto

package bb_clientd

import (
	cas "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/cas"
	filesystem "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem"
	virtual "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/virtual"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	builder "github.com/buildbarn/bb-storage/pkg/proto/configuration/builder"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                       protoimpl.MessageState                     `protogen:"open.v1"`
	Blobstore                   *blobstore.BlobstoreConfiguration          `protobuf:"bytes,1,opt,name=blobstore,proto3" json:"blobstore,omitempty"`
	MaximumMessageSizeBytes     int64                                      `protobuf:"varint,2,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	MaximumTreeSizeBytes        int64                                      `protobuf:"varint,11,opt,name=maximum_tree_size_bytes,json=maximumTreeSizeBytes,proto3" json:"maximum_tree_size_bytes,omitempty"`
	Global                      *global.Configuration                      `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	Mount                       *virtual.MountConfiguration                `protobuf:"bytes,4,opt,name=mount,proto3" json:"mount,omitempty"`
	GrpcServers                 []*grpc.ServerConfiguration                `protobuf:"bytes,5,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	Schedulers                  map[string]*builder.SchedulerConfiguration `protobuf:"bytes,6,rep,name=schedulers,proto3" json:"schedulers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FilePool                    *filesystem.FilePoolConfiguration          `protobuf:"bytes,7,opt,name=file_pool,json=filePool,proto3" json:"file_pool,omitempty"`
	OutputPathPersistency       *OutputPathPersistencyConfiguration        `protobuf:"bytes,8,opt,name=output_path_persistency,json=outputPathPersistency,proto3" json:"output_path_persistency,omitempty"`
	MaximumFileSystemRetryDelay *durationpb.Duration                       `protobuf:"bytes,9,opt,name=maximum_file_system_retry_delay,json=maximumFileSystemRetryDelay,proto3" json:"maximum_file_system_retry_delay,omitempty"`
	DirectoryCache              *cas.CachingDirectoryFetcherConfiguration  `protobuf:"bytes,10,opt,name=directory_cache,json=directoryCache,proto3" json:"directory_cache,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetBlobstore() *blobstore.BlobstoreConfiguration {
	if x != nil {
		return x.Blobstore
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetMaximumTreeSizeBytes() int64 {
	if x != nil {
		return x.MaximumTreeSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetMount() *virtual.MountConfiguration {
	if x != nil {
		return x.Mount
	}
	return nil
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetSchedulers() map[string]*builder.SchedulerConfiguration {
	if x != nil {
		return x.Schedulers
	}
	return nil
}

func (x *ApplicationConfiguration) GetFilePool() *filesystem.FilePoolConfiguration {
	if x != nil {
		return x.FilePool
	}
	return nil
}

func (x *ApplicationConfiguration) GetOutputPathPersistency() *OutputPathPersistencyConfiguration {
	if x != nil {
		return x.OutputPathPersistency
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumFileSystemRetryDelay() *durationpb.Duration {
	if x != nil {
		return x.MaximumFileSystemRetryDelay
	}
	return nil
}

func (x *ApplicationConfiguration) GetDirectoryCache() *cas.CachingDirectoryFetcherConfiguration {
	if x != nil {
		return x.DirectoryCache
	}
	return nil
}

type OutputPathPersistencyConfiguration struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	StateDirectoryPath         string                 `protobuf:"bytes,1,opt,name=state_directory_path,json=stateDirectoryPath,proto3" json:"state_directory_path,omitempty"`
	MaximumStateFileSizeBytes  int64                  `protobuf:"varint,2,opt,name=maximum_state_file_size_bytes,json=maximumStateFileSizeBytes,proto3" json:"maximum_state_file_size_bytes,omitempty"`
	MaximumStateFileAge        *durationpb.Duration   `protobuf:"bytes,3,opt,name=maximum_state_file_age,json=maximumStateFileAge,proto3" json:"maximum_state_file_age,omitempty"`
	LocalFileUploadConcurrency int64                  `protobuf:"varint,4,opt,name=local_file_upload_concurrency,json=localFileUploadConcurrency,proto3" json:"local_file_upload_concurrency,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *OutputPathPersistencyConfiguration) Reset() {
	*x = OutputPathPersistencyConfiguration{}
	mi := &file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputPathPersistencyConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPathPersistencyConfiguration) ProtoMessage() {}

func (x *OutputPathPersistencyConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPathPersistencyConfiguration.ProtoReflect.Descriptor instead.
func (*OutputPathPersistencyConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescGZIP(), []int{1}
}

func (x *OutputPathPersistencyConfiguration) GetStateDirectoryPath() string {
	if x != nil {
		return x.StateDirectoryPath
	}
	return ""
}

func (x *OutputPathPersistencyConfiguration) GetMaximumStateFileSizeBytes() int64 {
	if x != nil {
		return x.MaximumStateFileSizeBytes
	}
	return 0
}

func (x *OutputPathPersistencyConfiguration) GetMaximumStateFileAge() *durationpb.Duration {
	if x != nil {
		return x.MaximumStateFileAge
	}
	return nil
}

func (x *OutputPathPersistencyConfiguration) GetLocalFileUploadConcurrency() int64 {
	if x != nil {
		return x.LocalFileUploadConcurrency
	}
	return 0
}

var File_pkg_proto_configuration_bb_clientd_bb_clientd_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDesc = "" +
	"\n" +
	"3pkg/proto/configuration/bb_clientd/bb_clientd.proto\x12\"buildbarn.configuration.bb_clientd\x1a\x1egoogle/protobuf/duration.proto\x1a1pkg/proto/configuration/blobstore/blobstore.proto\x1a-pkg/proto/configuration/builder/builder.proto\x1a%pkg/proto/configuration/cas/cas.proto\x1a3pkg/proto/configuration/filesystem/filesystem.proto\x1a8pkg/proto/configuration/filesystem/virtual/virtual.proto\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\"\xe5\b\n" +
	"\x18ApplicationConfiguration\x12W\n" +
	"\tblobstore\x18\x01 \x01(\v29.buildbarn.configuration.blobstore.BlobstoreConfigurationR\tblobstore\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x02 \x01(\x03R\x17maximumMessageSizeBytes\x125\n" +
	"\x17maximum_tree_size_bytes\x18\v \x01(\x03R\x14maximumTreeSizeBytes\x12E\n" +
	"\x06global\x18\x03 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12T\n" +
	"\x05mount\x18\x04 \x01(\v2>.buildbarn.configuration.filesystem.virtual.MountConfigurationR\x05mount\x12T\n" +
	"\fgrpc_servers\x18\x05 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x12l\n" +
	"\n" +
	"schedulers\x18\x06 \x03(\v2L.buildbarn.configuration.bb_clientd.ApplicationConfiguration.SchedulersEntryR\n" +
	"schedulers\x12V\n" +
	"\tfile_pool\x18\a \x01(\v29.buildbarn.configuration.filesystem.FilePoolConfigurationR\bfilePool\x12~\n" +
	"\x17output_path_persistency\x18\b \x01(\v2F.buildbarn.configuration.bb_clientd.OutputPathPersistencyConfigurationR\x15outputPathPersistency\x12_\n" +
	"\x1fmaximum_file_system_retry_delay\x18\t \x01(\v2\x19.google.protobuf.DurationR\x1bmaximumFileSystemRetryDelay\x12j\n" +
	"\x0fdirectory_cache\x18\n" +
	" \x01(\v2A.buildbarn.configuration.cas.CachingDirectoryFetcherConfigurationR\x0edirectoryCache\x1av\n" +
	"\x0fSchedulersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12M\n" +
	"\x05value\x18\x02 \x01(\v27.buildbarn.configuration.builder.SchedulerConfigurationR\x05value:\x028\x01\"\xab\x02\n" +
	"\"OutputPathPersistencyConfiguration\x120\n" +
	"\x14state_directory_path\x18\x01 \x01(\tR\x12stateDirectoryPath\x12@\n" +
	"\x1dmaximum_state_file_size_bytes\x18\x02 \x01(\x03R\x19maximumStateFileSizeBytes\x12N\n" +
	"\x16maximum_state_file_age\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x13maximumStateFileAge\x12A\n" +
	"\x1dlocal_file_upload_concurrency\x18\x04 \x01(\x03R\x1alocalFileUploadConcurrencyBDZBgithub.com/buildbarn/bb-clientd/pkg/proto/configuration/bb_clientdb\x06proto3"

var (
	file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDesc), len(file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDescData
}

var file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),           // 0: buildbarn.configuration.bb_clientd.ApplicationConfiguration
	(*OutputPathPersistencyConfiguration)(nil), // 1: buildbarn.configuration.bb_clientd.OutputPathPersistencyConfiguration
	nil,                                              // 2: buildbarn.configuration.bb_clientd.ApplicationConfiguration.SchedulersEntry
	(*blobstore.BlobstoreConfiguration)(nil),         // 3: buildbarn.configuration.blobstore.BlobstoreConfiguration
	(*global.Configuration)(nil),                     // 4: buildbarn.configuration.global.Configuration
	(*virtual.MountConfiguration)(nil),               // 5: buildbarn.configuration.filesystem.virtual.MountConfiguration
	(*grpc.ServerConfiguration)(nil),                 // 6: buildbarn.configuration.grpc.ServerConfiguration
	(*filesystem.FilePoolConfiguration)(nil),         // 7: buildbarn.configuration.filesystem.FilePoolConfiguration
	(*durationpb.Duration)(nil),                      // 8: google.protobuf.Duration
	(*cas.CachingDirectoryFetcherConfiguration)(nil), // 9: buildbarn.configuration.cas.CachingDirectoryFetcherConfiguration
	(*builder.SchedulerConfiguration)(nil),           // 10: buildbarn.configuration.builder.SchedulerConfiguration
}
var file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_depIdxs = []int32{
	3,  // 0: buildbarn.configuration.bb_clientd.ApplicationConfiguration.blobstore:type_name -> buildbarn.configuration.blobstore.BlobstoreConfiguration
	4,  // 1: buildbarn.configuration.bb_clientd.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	5,  // 2: buildbarn.configuration.bb_clientd.ApplicationConfiguration.mount:type_name -> buildbarn.configuration.filesystem.virtual.MountConfiguration
	6,  // 3: buildbarn.configuration.bb_clientd.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	2,  // 4: buildbarn.configuration.bb_clientd.ApplicationConfiguration.schedulers:type_name -> buildbarn.configuration.bb_clientd.ApplicationConfiguration.SchedulersEntry
	7,  // 5: buildbarn.configuration.bb_clientd.ApplicationConfiguration.file_pool:type_name -> buildbarn.configuration.filesystem.FilePoolConfiguration
	1,  // 6: buildbarn.configuration.bb_clientd.ApplicationConfiguration.output_path_persistency:type_name -> buildbarn.configuration.bb_clientd.OutputPathPersistencyConfiguration
	8,  // 7: buildbarn.configuration.bb_clientd.ApplicationConfiguration.maximum_file_system_retry_delay:type_name -> google.protobuf.Duration
	9,  // 8: buildbarn.configuration.bb_clientd.ApplicationConfiguration.directory_cache:type_name -> buildbarn.configuration.cas.CachingDirectoryFetcherConfiguration
	8,  // 9: buildbarn.configuration.bb_clientd.OutputPathPersistencyConfiguration.maximum_state_file_age:type_name -> google.protobuf.Duration
	10, // 10: buildbarn.configuration.bb_clientd.ApplicationConfiguration.SchedulersEntry.value:type_name -> buildbarn.configuration.builder.SchedulerConfiguration
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_init() }
func file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_init() {
	if File_pkg_proto_configuration_bb_clientd_bb_clientd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDesc), len(file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bb_clientd_bb_clientd_proto = out.File
	file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_goTypes = nil
	file_pkg_proto_configuration_bb_clientd_bb_clientd_proto_depIdxs = nil
}
